//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Indent = new HashSet<Indent>();
            this.PurchaseOrder = new HashSet<PurchaseOrder>();
        }
    
        public string Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public string Keyword { get; set; }
        public string Employee_Email { get; set; }
        public string Sex { get; set; }
    
        public virtual ICollection<Indent> Indent { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrder { get; set; }
    }
}
