//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.Product = new HashSet<Product>();
        }
    
        public string stock_ID { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Quantity { get; set; }
        public System.DateTime Inventory_Date { get; set; }
        public Nullable<int> Threshold { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
    }
}
