//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.Indent = new HashSet<Indent>();
        }
    
        public string Payment_ID { get; set; }
        public string Payment_Method { get; set; }
        public Nullable<decimal> Payment_Money { get; set; }
        public System.DateTime Payment_Time { get; set; }
        public string Customer_ID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Indent> Indent { get; set; }
    }
}
