//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchasing
    {
        public string Detail_ID { get; set; }
        public Nullable<int> Purchasing_Quantity { get; set; }
        public Nullable<decimal> Purchasing_Price { get; set; }
        public string Product_Name { get; set; }
        public string PurchaseOrder_ID { get; set; }
        public string Product_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
