//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            this.Purchasing = new HashSet<Purchasing>();
        }
    
        public string PurchaseOrder_ID { get; set; }
        public Nullable<decimal> TotalPurchase_Price { get; set; }
        public System.DateTime Purchase_Date { get; set; }
        public string Supplier_ID { get; set; }
        public string Employee_ID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<Purchasing> Purchasing { get; set; }
    }
}
